# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'change_password_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.ApplicationModal)
        Form.resize(538, 385)
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 100, 441, 141))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.checkPasswordLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.checkPasswordLabel.setFont(font)
        self.checkPasswordLabel.setObjectName("checkPasswordLabel")
        self.gridLayout.addWidget(self.checkPasswordLabel, 1, 0, 1, 1)
        self.passwordLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.passwordLabel.setFont(font)
        self.passwordLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.passwordLabel.setObjectName("passwordLabel")
        self.gridLayout.addWidget(self.passwordLabel, 0, 0, 1, 1)
        self.passwordLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.passwordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.gridLayout.addWidget(self.passwordLineEdit, 0, 1, 1, 1)
        self.checkPasswordLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.checkPasswordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.checkPasswordLineEdit.setObjectName("checkPasswordLineEdit")
        self.gridLayout.addWidget(self.checkPasswordLineEdit, 1, 1, 1, 1)
        self.changePasswordButton = QtWidgets.QPushButton(Form)
        self.changePasswordButton.setGeometry(QtCore.QRect(170, 270, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.changePasswordButton.setFont(font)
        self.changePasswordButton.setObjectName("changePasswordButton")
        self.requirementsLabel = QtWidgets.QLabel(Form)
        self.requirementsLabel.setGeometry(QtCore.QRect(30, 40, 451, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.requirementsLabel.setFont(font)
        self.requirementsLabel.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.requirementsLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.requirementsLabel.setTextFormat(QtCore.Qt.AutoText)
        self.requirementsLabel.setScaledContents(False)
        self.requirementsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.requirementsLabel.setObjectName("requirementsLabel")
        self.errorLabel = QtWidgets.QLabel(Form)
        self.errorLabel.setGeometry(QtCore.QRect(10, 330, 471, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.errorLabel.setFont(font)
        self.errorLabel.setText("")
        self.errorLabel.setObjectName("errorLabel")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Изменение пароля"))
        self.checkPasswordLabel.setText(_translate("Form", "Подтвердите пароль:"))
        self.passwordLabel.setText(_translate("Form", "Пароль:"))
        self.changePasswordButton.setText(_translate("Form", "Изменить пароль"))
        self.requirementsLabel.setText(_translate("Form", "Минимальная длина пароля - 12 символов"))
