# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'leaders_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.ApplicationModal)
        Form.resize(494, 461)
        self.leadersLabel = QtWidgets.QLabel(Form)
        self.leadersLabel.setGeometry(QtCore.QRect(150, 10, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.leadersLabel.setFont(font)
        self.leadersLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.leadersLabel.setObjectName("leadersLabel")
        self.leadersTable = QtWidgets.QTableWidget(Form)
        self.leadersTable.setGeometry(QtCore.QRect(10, 70, 461, 371))
        self.leadersTable.setObjectName("leadersTable")
        self.leadersTable.setColumnCount(0)
        self.leadersTable.setRowCount(0)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Лидеры"))
        self.leadersLabel.setText(_translate("Form", "Таблица лидеров"))
