# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_game_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.ApplicationModal)
        Form.resize(574, 458)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(60, 140, 463, 161))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.difficulty_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.difficulty_label.setFont(font)
        self.difficulty_label.setObjectName("difficulty_label")
        self.verticalLayout.addWidget(self.difficulty_label)
        self.easyDifficultyButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.easyDifficultyButton.setFont(font)
        self.easyDifficultyButton.setChecked(True)
        self.easyDifficultyButton.setObjectName("easyDifficultyButton")
        self.difficultyButtonGroup = QtWidgets.QButtonGroup(Form)
        self.difficultyButtonGroup.setObjectName("difficultyButtonGroup")
        self.difficultyButtonGroup.addButton(self.easyDifficultyButton)
        self.verticalLayout.addWidget(self.easyDifficultyButton)
        self.normalDifficultyButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.normalDifficultyButton.setFont(font)
        self.normalDifficultyButton.setObjectName("normalDifficultyButton")
        self.difficultyButtonGroup.addButton(self.normalDifficultyButton)
        self.verticalLayout.addWidget(self.normalDifficultyButton)
        self.hardDifficultyButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.hardDifficultyButton.setFont(font)
        self.hardDifficultyButton.setObjectName("hardDifficultyButton")
        self.difficultyButtonGroup.addButton(self.hardDifficultyButton)
        self.verticalLayout.addWidget(self.hardDifficultyButton)
        self.newGameButton = QtWidgets.QPushButton(Form)
        self.newGameButton.setGeometry(QtCore.QRect(60, 330, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.newGameButton.setFont(font)
        self.newGameButton.setObjectName("newGameButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Новая игра"))
        self.difficulty_label.setText(_translate("Form", "Выберите уровень сложности:"))
        self.easyDifficultyButton.setText(_translate("Form", "лёгкий"))
        self.normalDifficultyButton.setText(_translate("Form", "обычный"))
        self.hardDifficultyButton.setText(_translate("Form", "сложный"))
        self.newGameButton.setText(_translate("Form", "Начать игру"))
