# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registration_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.ApplicationModal)
        Form.resize(547, 358)
        self.registrationButton = QtWidgets.QPushButton(Form)
        self.registrationButton.setGeometry(QtCore.QRect(190, 250, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.registrationButton.setFont(font)
        self.registrationButton.setObjectName("registrationButton")
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(90, 90, 341, 141))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.passwordLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.passwordLabel.setFont(font)
        self.passwordLabel.setObjectName("passwordLabel")
        self.gridLayout.addWidget(self.passwordLabel, 1, 0, 1, 1)
        self.loginLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.loginLabel.setFont(font)
        self.loginLabel.setObjectName("loginLabel")
        self.gridLayout.addWidget(self.loginLabel, 0, 0, 1, 1)
        self.loginLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.loginLineEdit.setObjectName("loginLineEdit")
        self.gridLayout.addWidget(self.loginLineEdit, 0, 1, 1, 1)
        self.passwordLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.passwordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.gridLayout.addWidget(self.passwordLineEdit, 1, 1, 1, 1)
        self.errorLabel = QtWidgets.QLabel(Form)
        self.errorLabel.setGeometry(QtCore.QRect(20, 295, 471, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.errorLabel.setFont(font)
        self.errorLabel.setText("")
        self.errorLabel.setObjectName("errorLabel")
        self.requirementsLabel = QtWidgets.QLabel(Form)
        self.requirementsLabel.setGeometry(QtCore.QRect(30, 30, 451, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.requirementsLabel.setFont(font)
        self.requirementsLabel.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.requirementsLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.requirementsLabel.setTextFormat(QtCore.Qt.AutoText)
        self.requirementsLabel.setScaledContents(False)
        self.requirementsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.requirementsLabel.setObjectName("requirementsLabel")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Регистрация"))
        self.registrationButton.setText(_translate("Form", "Зарегистрироваться"))
        self.passwordLabel.setText(_translate("Form", "Пароль:"))
        self.loginLabel.setText(_translate("Form", "Логин:"))
        self.requirementsLabel.setText(_translate("Form", "Минимальная длина пароля - 12 символов"))
