# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sudoku_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.ApplicationModal)
        Form.resize(961, 872)
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 20, 241, 91))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.attemptsLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.attemptsLabel.setFont(font)
        self.attemptsLabel.setObjectName("attemptsLabel")
        self.gridLayout.addWidget(self.attemptsLabel, 2, 0, 1, 1)
        self.timeLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.timeLabel.setFont(font)
        self.timeLabel.setObjectName("timeLabel")
        self.gridLayout.addWidget(self.timeLabel, 0, 0, 1, 1)
        self.timeDisplayLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.timeDisplayLabel.setFont(font)
        self.timeDisplayLabel.setText("")
        self.timeDisplayLabel.setObjectName("timeDisplayLabel")
        self.gridLayout.addWidget(self.timeDisplayLabel, 0, 1, 1, 1)
        self.attemptsDisplayLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.attemptsDisplayLabel.setFont(font)
        self.attemptsDisplayLabel.setText("")
        self.attemptsDisplayLabel.setObjectName("attemptsDisplayLabel")
        self.gridLayout.addWidget(self.attemptsDisplayLabel, 2, 1, 1, 1)
        self.checkButton = QtWidgets.QPushButton(Form)
        self.checkButton.setGeometry(QtCore.QRect(10, 790, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkButton.setFont(font)
        self.checkButton.setObjectName("checkButton")
        self.errorLabel = QtWidgets.QLabel(Form)
        self.errorLabel.setGeometry(QtCore.QRect(20, 840, 921, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.errorLabel.setFont(font)
        self.errorLabel.setText("")
        self.errorLabel.setObjectName("errorLabel")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Решите судоку"))
        self.attemptsLabel.setText(_translate("Form", "Попытки:"))
        self.timeLabel.setText(_translate("Form", "Время:"))
        self.checkButton.setText(_translate("Form", "Проверить"))
